### PR TITLE
Update `(write access required)` message

### PR DESCRIPTION
**Pull request by Pantelis-Santorinios**
Changing `(write access required)` to `(write access to the repository is required to view the log)`  for clarity

### CODE REVIEW

**Comment by jurre** [comment]
Thanks @Pantelis-Santorinios! There's a couple of tests that check for this string, would you mind updating those as well? 🙇

**Comment by jurre** [comment]
Looking great, if you could just run `npm run package` and commit the results this looks good to go to me!

**Comment by mctofu** [comment]
Assuming you are using a codespace, these are the steps needed to get `npm run package` to get the right output (should work locally too if you have nvm). 

```
#### install the expected npm version
$ nvm install 
Found '/workspaces/dependabot-action/.nvmrc' with version <16.19.0>
Downloading and installing node v16.19.0...
Downloading https://nodejs.org/dist/v16.19.0/node-v16.19.0-linux-x64.tar.xz...
############################################################################################################################################### 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v16.19.0 (npm v8.19.3)
```
```
#### make sure we've installed the right stuff for this npm version
$ npm clean-install

> dependabot-updater-action@2.9.0 prepare
> husky install

husky - Git hooks installed

added 780 packages, and audited 781 packages in 12s

173 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```
```
#### package it all up
$ npm run package


> dependabot-updater-action@2.9.0 package
> ncc build -o dist/main src/main.ts --source-map --license licenses.txt && ncc build -o dist/cleanup src/cleanup.ts --source-map --license licenses.txt

ncc: Version 0.36.1
ncc: Compiling file index.js into CJS
ncc: Using typescript@5.2.2 (local user-provided)
  40kB  dist/main/sourcemap-register.js
  43kB  dist/main/build/Release/cpufeatures.node
  50kB  dist/main/pagent.exe
  91kB  dist/main/lib/protocol/crypto/build/Release/sshcrypto.node
 130kB  dist/main/licenses.txt
2843kB  dist/main/index.js
2900kB  dist/main/index.js.map
2900kB  dist/main/index.js.map
6097kB  [8333ms] - ncc 0.36.1
ncc: Version 0.36.1
ncc: Compiling file index.js into CJS
ncc: Using typescript@5.2.2 (local user-provided)
  40kB  dist/cleanup/sourcemap-register.js
  43kB  dist/cleanup/build/Release/cpufeatures.node
  50kB  dist/cleanup/pagent.exe
  68kB  dist/cleanup/licenses.txt
  91kB  dist/cleanup/lib/protocol/crypto/build/Release/sshcrypto.node
1092kB  dist/cleanup/index.js
1274kB  dist/cleanup/index.js.map
1274kB  dist/cleanup/index.js.map
2658kB  [6185ms] - ncc 0.36.1
```

**Comment by landongrindheim** [comment]
> Assuming you are using a codespace

☝️ In my experience, the `npm run package` output can vary between MacOS and Linux. Doing this in Codespaces will make this a little smoother (assuming the command was run on MacOS) 🙂

**Comment by Pantelis-Santorinios** [comment]
Indeed it was a codespace and that seems to did the trick. Thanks.

**Review by landongrindheim — APPROVED** [review]

**Pull request merged**
