### PR TITLE
Upgrade from node16 to node20

### PR DESCRIPTION
**Pull request by Nishnha**
Node16 is now EOL. The next LTS release is node18 which has support until 2025, but node20 has support until 2026.

https://nodejs.dev/en/about/releases/

### CODE REVIEW

**Comment by jakecoffman** [comment]
We need to update .nvmrc too.

**Review by jakecoffman — APPROVED** [review]

**Comment by Nishnha** [comment]
It looks like the integration test in https://github.com/github/dependabot-action/actions/runs/6266275183/job/17018392140?pr=1050 ran successfully, but it somehow got stuck? It ran for ~2 hours before I cancelled it. I am also able to reproduce this on my machine by running `npm run test-integration`

It seems we have open handles preventing jest from closing and we should investigate them in a separate issue.

I ended up committing 69be7603c5974671c15544e4ba6647fd7143185a as a patch to quick fix this, since it seems to be a well known bug that jest can just hang when using the `--detectOpenHandles` flag: https://github.com/jestjs/jest/issues/9473

**Comment by Nishnha** [comment]
I'm going to test running a Dependabot update with this branch by running `.dependabot actions set-branch nishnha/use-node-20` and attempting a dependabot recreate on https://github.com/github/dependabot-api/pull/4450

**Comment by Nishnha** [comment]
That did not work. I think the actions chatops are broken? 
https://github.slack.com/archives/C03QKEVQ761/p1695337655858119

**Pull request merged**
