### PR TITLE
To retrieve the JobToken and CredToken directly from the Actions Environment instead of the Input Payload

### PR DESCRIPTION
**Pull request by honeyankit**
## Context

With the use of the [secret source](https://github.com/github/dependabot-updates/issues/3591.), we provide job tokens/cred tokens to dynamic workflow via Twirp API call instead of passing those tokens as a input parameters to dynamic workflow for Dependabot on Actions. So, we have removed the tokens from the dynamic workflow's payload (behind a feature flag) in Dependabot's API, but the same payload in the dynamic workflow is used by [dependabot-actions service (via webhook) to retrieve the job and cred tokens](https://github.com/github/dependabot-action/blob/main/src/inputs.ts#L77-L97). 

In this PR, we are using the Actions CI environment to retrieve the job/cred token which was earlier passed via input job parameters to Dependabot-action service. 

```
// Retrieve jobToken and credentialsToken from environment variables
const jobToken = process.env.GITHUB_DEPENDABOT_JOB_TOKEN
const credentialsToken = process.env.GITHUB_DEPENDABOT_CRED_TOKEN
```

## Approach  
After using the secret source token, we configure the Actions' environment variables through the secret context, embedding both job and credential tokens. This setup ensures that during the CI run of Actions, these tokens are accessible as environment variables for the Dependabot-actions service, allowing for their retrieval

### CODE REVIEW

**Review by pavera — APPROVED** [review]
LGTM

**Comment by honeyankit** [comment]
Need to support the backward compatibility so need to support token from both jobParameters and Actions environment variables

**Comment by honeyankit** [comment]
Tested this branch to retrieve jobToken and CredToken directly from the Action environment and it works:

image

**Comment by honeyankit** [comment]
After merge conflict, I tested my changes successfully 

image

**Review by abdulapopoola — APPROVED** [review]

**Pull request merged**
