### PR TITLE
Concurrent Execution with `Promise.all` for Enhanced Resource Utilization ✈️

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
Hello,

This PR aims to provide a minor performance boost by implementing concurrent execution of a function using `Promise.all`. This enhancement is expected to improve overall performance and optimize the utilization of hardware resources. By leveraging concurrent execution, we can achieve more efficient and effective utilization of system resources, resulting in improved performance.

### CODE REVIEW

**Comment by jeffwidman** [comment]
👋 Hey @sanjaiyan-dev thanks for stopping by and sorry for the slow review. 😢 

This seems very reasonable to me, so I rebased to kickstart CI... looks like there's a lint failure and also you need to check in `dist` contents.

Rebuilding `dist` is pretty straightforward--run `npm package build` within a codespace (or locally as long as you've got the correct npm/node versions).

Let me know if you get stuck!

**Review by jeffwidman — COMMENTED** [review]
Kickstarting CI

**Review by jeffwidman — APPROVED** [review]

**Review by jeffwidman — CHANGES_REQUESTED** [review]
This is embarrassing, but my approval happened because I got confused by the GitHub UI... I was just trying to get CI to trigger! Probably because we're using Merge Queue's feature on this repo, and I'm still getting used to them.

Anyway, it looks like the issues I mentioned before are still occuring... can you fix the lint issue and also rebuild `dist`?

Once that happens, this looks good to go IMO.

Thanks!

**Comment by sanjaiyan-dev** [comment]
> This is embarrassing, but my approval happened because I got confused by the GitHub UI... I was just trying to get CI to trigger! Probably because we're using Merge Queue's feature on this repo, and I'm still getting used to them.
> 
> Anyway, it looks like the issues I mentioned before are still occuring... can you fix the lint issue and also rebuild `dist`?
> 
> Once that happens, this looks good to go IMO.
> 
> Thanks!

Hi, extremely sorry for the delay, hope I fixed the lint related issues :)

**Review by jeffwidman — APPROVED** [review]
Thanks!

**Pull request merged**
